name: Generate 3D Contribution City

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate 3D Contribution City
        uses: lowlighter/metrics@latest
        with:
          filename: profile-3d-city.svg
          token: ${{ secrets.GITHUB_TOKEN }}

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          config_timezone: Asia/Kolkata

          optimize: css, xml
          committer_branch: main

      - name: Commit generated SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🏙️ Update 3D contribution city"
          branch: main
          file_pattern: profile-3d-city.svg
